### ISSUE TITLE
keyError

### ISSUE THREAD

**Issue by ht-Leung** [luyh20/FGC-GraspNet#7]
hi @luyh20 
When i run demo, I meet the problem:
Traceback (most recent call last):
  File "demo.py", line 159, in <module>
    demo(data_dir)
  File "demo.py", line 151, in demo
    gg = get_grasps(net, end_points)
  File "demo.py", line 105, in get_grasps
    end_points = net(end_points)
  File "/home/ryze/anaconda3/envs/ffgc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ryze/GRASP/FGC-GraspNet/models/FGC_graspnet.py", line 160, in forward
    _, _, _, end_points = match_grasp_view_and_label(end_points)
  File "/home/ryze/GRASP/FGC-GraspNet/utils/label_generation.py", line 126, in match_grasp_view_and_label
    template_views_rot = end_points['batch_grasp_view_rot'] # (B, Ns, V, 3, 3)
KeyError: 'batch_grasp_view_rot'

how to fix it?

**Comment by luyh20** [comment]
there are some issues with the code here, "_, _, _, end_points = match_grasp_view_and_label(end_points)", this line should be commented out in the demo mode. I fixed it, and you could pull the code and try again.

**Comment by ht-Leung** [comment]
thank you for your help. I've run it successfully.😉
